---
- name: Generate TLS Server Cert secret manifest
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/infra/Secret-server-tls.yaml.j2"
    dest: "{{ tpa_single_node_server_secret }}"
    mode: "0600"
  vars:
    tpa_single_node_trust_tls_cert_pem: "{{ lookup('file', tpa_single_node_trust_server_cert_tls_crt_path) }}"
    tpa_single_node_trust_tls_cert_key: "{{ lookup('file', tpa_single_node_trust_server_cert_tls_key_path) }}"


- name: Generate OIDC secret manifest
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/infra/Secret-oidc.yaml.j2"
    dest: "{{ tpa_single_node_server_secret }}"
    mode: "0600"

- name: Apply server secret manifest
  ansible.builtin.command:
    cmd: "podman kube play {{ tpa_single_node_server_secret }}"
  changed_when: false
